"""agents add provider

Revision ID: 39054fd85c26
Revises: a2502ebad4f4
Create Date: 2026-08-10 13:05:55.585523

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39054fd85c26"
down_revision: str | Sequence[str] | None = "a2502ebad4f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先允许为空地加列
    op.add_column("agents", sa.Column("provider", sa.String(length=100), nullable=True))
    # 2. 给已有行填默认值
    op.execute("UPDATE agents SET provider = 'mock' WHERE provider IS NULL")
    # 3. 再改成非空
    op.alter_column("agents", "provider", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "provider")
    # ### end Alembic commands ###
